// Mocks generated by Mockito 5.4.6 from annotations
// in yall/test/providers/post_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:yall/models/account.dart' as _i7;
import 'package:yall/models/platform_type.dart' as _i4;
import 'package:yall/models/post_result.dart' as _i2;
import 'package:yall/services/social_platform_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostResult_0 extends _i1.SmartFake implements _i2.PostResult {
  _FakePostResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SocialPlatformService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialPlatformService extends _i1.Mock
    implements _i3.SocialPlatformService {
  MockSocialPlatformService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PlatformType get platformType =>
      (super.noSuchMethod(
            Invocation.getter(#platformType),
            returnValue: _i4.PlatformType.mastodon,
          )
          as _i4.PlatformType);

  @override
  String get platformName =>
      (super.noSuchMethod(
            Invocation.getter(#platformName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#platformName),
            ),
          )
          as String);

  @override
  int get characterLimit =>
      (super.noSuchMethod(Invocation.getter(#characterLimit), returnValue: 0)
          as int);

  @override
  List<String> get requiredCredentialFields =>
      (super.noSuchMethod(
            Invocation.getter(#requiredCredentialFields),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i6.Future<bool> authenticate(_i7.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [account]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i2.PostResult> publishPost(
    String? content,
    _i7.Account? account,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#publishPost, [content, account]),
            returnValue: _i6.Future<_i2.PostResult>.value(
              _FakePostResult_0(
                this,
                Invocation.method(#publishPost, [content, account]),
              ),
            ),
          )
          as _i6.Future<_i2.PostResult>);

  @override
  _i6.Future<bool> validateConnection(_i7.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#validateConnection, [account]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  bool isContentValid(String? content) =>
      (super.noSuchMethod(
            Invocation.method(#isContentValid, [content]),
            returnValue: false,
          )
          as bool);

  @override
  int getRemainingCharacters(String? content) =>
      (super.noSuchMethod(
            Invocation.method(#getRemainingCharacters, [content]),
            returnValue: 0,
          )
          as int);

  @override
  _i2.PostResult createSuccessResult(String? content) =>
      (super.noSuchMethod(
            Invocation.method(#createSuccessResult, [content]),
            returnValue: _FakePostResult_0(
              this,
              Invocation.method(#createSuccessResult, [content]),
            ),
          )
          as _i2.PostResult);

  @override
  _i2.PostResult createFailureResult(
    String? content,
    String? errorMessage,
    _i2.PostErrorType? errorType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createFailureResult, [
              content,
              errorMessage,
              errorType,
            ]),
            returnValue: _FakePostResult_0(
              this,
              Invocation.method(#createFailureResult, [
                content,
                errorMessage,
                errorType,
              ]),
            ),
          )
          as _i2.PostResult);

  @override
  _i2.PostResult handleError(
    String? content,
    dynamic error, {
    _i2.PostErrorType? defaultErrorType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #handleError,
              [content, error],
              {#defaultErrorType: defaultErrorType},
            ),
            returnValue: _FakePostResult_0(
              this,
              Invocation.method(
                #handleError,
                [content, error],
                {#defaultErrorType: defaultErrorType},
              ),
            ),
          )
          as _i2.PostResult);

  @override
  bool validateCredentials(_i7.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#validateCredentials, [account]),
            returnValue: false,
          )
          as bool);

  @override
  bool hasRequiredCredentials(_i7.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#hasRequiredCredentials, [account]),
            returnValue: false,
          )
          as bool);
}
