name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-builds:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'
        channel: 'stable'
        
    - name: Install Linux dependencies
      if: matrix.platform == 'linux'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev liblzma-dev
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Build ${{ matrix.platform }}
      run: flutter build ${{ matrix.platform }} --release
      
    - name: Test build artifacts
      run: |
        if [ "${{ matrix.platform }}" = "linux" ]; then
          ls -la build/linux/x64/release/bundle/
          file build/linux/x64/release/bundle/yall
        else
          dir build\windows\x64\runner\Release\
          if exist build\windows\x64\runner\Release\yall.exe echo "Windows build successful"
        fi
      shell: bash
